version: "3.8"
services:
  acme-api-consumer:
    build: .
    container_name: "docker-app"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
