version: "3.8"
services:
  acme-api-consumer:
    build: acme-api-consumer
    container_name: "docker-app"
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017